FROM node:16
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build
# SERVICE PORT
ENV SERVICE_PORT=7000



# EXPOSE PORT, SHOULD BE SAME AS SERVICE PORT
EXPOSE 7000
CMD [ "node", "./dist/main.js" ]